galaxy_info:
  author: Mats Blomdahl
  description: PostgreSQL server provisioning.
  company: National Library of Sweden

  license: Apache-2.0

  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - postgresql

dependencies: []
