"""Add column 'is_deleted' to users table.

Revision ID: 14302cf25610
Revises: 750e1f83b191
Create Date: 2022-06-07 16:35:52.870887

"""

from __future__ import absolute_import, division, print_function, unicode_literals

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision = '14302cf25610'
down_revision = '750e1f83b191'
branch_labels = None
depends_on = None


def upgrade():
    """Add column 'is_deleted' to users table."""
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_deleted = false")
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_deleted', nullable=False)

    ### end Alembic commands ###


def downgrade():
    """Remove column 'is_deleted' to users table."""
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    ### end Alembic commands ###
