---

- name: nodejs 7 repo
  yum_repository:
    name: nodesource
    description: Node.js Packages for Enterprise Linux 7 - $basearch
    baseurl: https://rpm.nodesource.com/pub_7.x/el/7/$basearch
    gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
  tags: nodejs

- name: install nodejs-7.10.1
  yum: name=nodejs-7.10.1 state=present
  tags: nodejs

- name: check if npm version is 5.3.x
  shell: npm -v
  register: npm_version
  changed_when: false
  tags: nodejs

- name: npm-install npm@5.3 globally
  npm: name=npm@5.3 global=yes state=present
  when: not npm_version.stdout.startswith('5.3.')
  tags: nodejs

- name: install gcc-c++ and make (as per nodejs recommendations)
  yum: name={{ item }} state=present
  with_items:
    - gcc-c++
    - make
  tags: nodejs

...
