---

- name: install python-psycopg2
  yum: name=python-psycopg2 state=present
  tags: postgresql

- name: postgres 9.4 repo
  yum_repository:
    name: pgdg94
    description: PostgreSQL 9.4 $releasever - $basearch
    baseurl: https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-$releasever-$basearch
  tags: postgresql

- name: install postgresql94-server
  yum: name=postgresql94-server disable_gpg_check=yes state=present
  register: postgresql94_server_install
  tags: postgresql

- name: initialize postgresql database in PGDATA
  shell: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  when: postgresql94_server_install.changed
  tags: postgresql

- name: configure postgresql pg_hba.conf to trust local connections
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.4/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600
  tags: postgresql

- name: postgresql running and enabled
  service: name=postgresql-9.4 state=started enabled=yes
  tags: postgresql

- name: create '{{ postgresql_db }}' postgresql db
  postgresql_db:
    login_host: 127.0.0.1
    port: 5432
    name: "{{ postgresql_db }}"
  become: yes
  become_user: "{{ postgresql_user }}"
  tags: postgresql

...
